config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/products/:id/add', to: 'order_lines#add_to_basket', as: 'add_to_basket'
  get '/order_lines/:id/add', to: 'order_lines#add', as: 'add_order_lines'
  get '/order_lines/:id/remove', to: 'order_lines#remove', as: 'remove_order_lines'

  get  "/postcodecheckers", to: "postcodecheckers#check_address"
  get  "/confirmation/:order_id", to: "payments#confirmation", as:"confirmation"
  get  "/about", to: "pages#about", as:"about"
  get  "/recipe/:recipe_id", to: "recipes#show", as:"recipe"
  get "/recipe/:recipe_id/order", to: "order_lines#order_recipe", as: "order_recipe"


  get "/orders/history", to: "orders#history", as: "order_history"
  get "/order_lines/:id/reorder", to: "order_lines#reorder", as: "reorder"

  post   "/subscriptions", to: "pages#create_subscription", as: "subscriptions"


  root to: 'pages#home'
    resources :users, only: [:new, :create, :edit, :update] do
      resources :contacts, only: [:update]
    end
    resources :orders, only: [:index] do
      resources :payments, only: [:new, :create]
    end
    resources :products, only: [:index, :show] do
      resources :order_lines, only: [:create]
    end

    post  "/postcodecheckers", to: "postcodecheckers#check_address"
    get  "/checkout", to: "payments#checkout"

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :producer
  has_many :ingredients
  has_many :products, through: :ingredients
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_after_action :verify_authorized
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @recipe = Recipe.find(params[:recipe_id])
    authorize @recipe
  end


end

app/views/recipes/show.html.erb
<div class="recipe-page">
  <div class="recipe-section">
    <h3 style="font-size: 1em; color: #c0c0c0">recipe</h3>
    <div class="recipe-banner" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.5)), url(<%= @recipe.photo %>);">
      <div class="recipe-banner-difficulty">
        <div class="dbuy ingredients
ifficulty-text">
          Difficulty: <%= @recipe.difficulty %>
        </div>
      </div>
      <div class="recipe-banner-bottom">

        <h2><%= @recipe.title %></h2>
        <div class="recipe-banner-avatar-name">
          <div class="recipe-banner-producer-avatar" style="background-image: url(<%= @recipe.producer.photo %>)">
          </div>
          <div class="recipe-banner-producer-name">
            <%= @recipe.producer.name %>
          </div>

        </div>
      </div>
    </div>
    <div style="display: flex">
      <div style="flex: 1 1 auto; margin-right: 50px">
        <h3 class="recipe-title">ingredients</h3>
          <% @recipe.products.each do |product| %>
        <p class="recipe-para"><%= product.name %></p>
      <% end %>
      </div>
      <div style="flex: 1 1 auto; margin-right: 50px">
        <h3 class="recipe-title">method</h3>
        <% @recipe.instructions.each_with_index do |instruction, index|%>
        <p class="recipe-para"><strong>step <%= index + 1 %></strong> <%= instruction %></p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="buy-ingredients">
    <h3 style="font-size: 1em; color: #c0c0c0">buy ingredients</h3>
    <% @recipe.products.each do |recipe| %>
      <div class="ingredient-card">
        <div class="ingredient-card-photo-info">
          <div class="ingredient-card-photo" style="background-image: url(<%= recipe.photo %>)">
            <div class="ingredient-card-producer-avatar" style="background-image: url(<%= recipe.producer.photo %>)"></div>
          </div>
          <div class="ingredient-info">
            <h3 class="basket-item-name ingredient-name"><%= recipe.name %></h3>
            <p style="font-size: 12px; margin: 0px; font-weight: 500; color: #FFB96E; font-family: 'Montserrat'"><%= humanized_money_with_symbol(recipe.price) %></p>
          </div>
        </div>
        <div class="ingredient-add-button">
          <a class="ingredient-add-icon" href= <%=add_to_basket_path(recipe.id)%> <img src="white-plus-icon.svg" alt=""><%= image_tag 'white-plus-icon.svg', :class => "ingredient-add-icon" %> </a>
        </div>
      </div>
    <% end %>
    <a href="<%=order_recipe_path(@recipe)%>" style="margin-bottom: 10px; margin-right: 5px;" class="add-to-cart-btn">
      <h3 style="font-size:16px; margin-top: 5px; margin-bottom: 5px; background-color: #FFB96E; color: white !important; border-bottom: none !important; padding: 10px 20px 10px 20px;">
        buy all ingredients
      </h3>
    </a>
  </div>

</div>
<div class="footer-spacer"></div>


<!--

  <div class="recipe-content">
    <div>
      <h1><%= @recipe.title %></h1>
    </div>

    <% @recipe.products.each do |recipe| %>
      <div class="recipe-product-card">


        <div class="recipe-card-image" style="background-image: url(<%= recipe.photo %>)">
        </div>

        <div class="recipe-card-producer-avatar" style="background-image: url(<%= @recipe.producer.photo %>)">
        </div>

          <%= recipe.name %>
        <div class="recipe-product-button">
          <a href= <%=add_to_basket_path(recipe.id)%> class="add-to-cart-btn">ADD</a>
        </div>
      </div>
    <% end %>
  </div>





  <h2>Products used in the recipe: </h2>
  <%= @recipe.description %>
  <%= @recipe.instructions %>
  <%= @recipe.difficulty %>

  <%= @recipe.producer.name %>
  <%= @recipe.producer.city %>
  <%= @recipe.producer.photo %>
  <%= @recipe.producer.description %>
 -->