config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/products/:id/add', to: 'order_lines#add_to_basket', as: 'add_to_basket'
  get '/order_lines/:id/add', to: 'order_lines#add', as: 'add_order_lines'
  get '/order_lines/:id/remove', to: 'order_lines#remove', as: 'remove_order_lines'

  get  "/postcodecheckers", to: "postcodecheckers#check_address"
  get  "/confirmation/:order_id", to: "payments#confirmation", as:"confirmation"
  get  "/about", to: "pages#about", as:"about"
  get  "/recipe/:recipe_id", to: "recipes#show", as:"recipe"
  get "/recipe/:recipe_id/order", to: "order_lines#order_recipe", as: "order_recipe"


  get "/orders/history", to: "orders#history", as: "order_history"
  get "/order_lines/:id/reorder", to: "order_lines#reorder", as: "reorder"

  post   "/subscriptions", to: "pages#create_subscription", as: "subscriptions"


  root to: 'pages#home'
    resources :users, only: [:new, :create, :edit, :update] do
      resources :contacts, only: [:update]
    end
    resources :orders, only: [:index] do
      resources :payments, only: [:new, :create]
    end
    resources :products, only: [:index, :show] do
      resources :order_lines, only: [:create]
    end

    post  "/postcodecheckers", to: "postcodecheckers#check_address"
    get  "/checkout", to: "payments#checkout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :subcategory, presence: true, inclusion: ["vegetables", "fruits", "meat", "fish", "dairy & eggs", "bakery", "wine & drinks", "pantry", "deli"]
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :product
end

app/models/nutrient.rb
class Nutrient < ApplicationRecord
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_lines
  has_many :products, through: :order_lines
  monetize :amount_cents

  validates :status, presence: true, inclusion: ["new","paid"]
end

app/models/order_line.rb
class OrderLine < ApplicationRecord
  belongs_to :order
  belongs_to :product
  has_one :user, through: :order
end

app/models/post_code_checker.rb
class PostCodeChecker < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

 #validates :address, presence: true

end

app/models/producer.rb
class Producer < ApplicationRecord
 #after_validation :geocode, if: :will_save_change_to_address?
 has_many :recipes
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :producer
  belongs_to :category
  has_many :order_lines
  has_one :nutrient
  has_many :orders, through: :order_lines
  monetize :price_cents
  has_many :ingredients
  has_many :recipes, through: :ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :producer
  has_many :ingredients
  has_many :products, through: :ingredients
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :email, presence: true, uniqueness: true, format: { with: /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\z/i }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :orders
         has_many :products, through: :orders
         has_one :contact

  def after_sign_in_path_for(resource)
    products_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_after_action :verify_authorized

  def update
    @contact = Contact.find_by(user_id: current_user.id)
    if @contact.update(contact_params)
      raise
      #redirect_to orders_path
    else
      render :update
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:address, :phone)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def history
    if !current_user.nil?
      @orders = Order.where(user_id: current_user.id)
      authorize @orders
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :about, :create_subscription]

  def home
    @recipes = Recipe.all.first(5)
    @farmers = Producer.where(speciality: "farmer").first(10)
    @butchers = Producer.where(speciality: "butcher").first(10)
    @fishermen = Producer.where(speciality: "fishermen").first(10)
    @dairys = Producer.where(speciality: "dairy").first(10)
    @bakers = Producer.where(speciality: "baker").first(10)
    @winemakers = Producer.where(speciality: "winemaker").first(10)
    @cooks = Producer.where(speciality: "cook").first(10)
   # @deli_creatives = Producer.where(speciality: "deli").first(5)
  end

  def about
    @subscription = Subscription.new
    authorize @subscription
  end

  def create_subscription
    if !subscription_params.nil?
      @subscription = Subscription.new
      @subscription = Subscription.create(subscription_params)
      if @subscription.save
        # flash[:create_subscription] = "Order has been added to your basket."
        redirect_to about_path
      else
        render :about
      end
    end
    authorize @subscription
  end

  private

  def subscription_params
    params.require(:subscription).permit(:email)
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  skip_after_action :verify_authorized
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :set_order, except: :confirmation

  # def new
  #   @order= Order.find(params[:order_id])
  # end

  def create

    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @order.amount_cents,
    description:  "Payment for order #{@order.id}",
    currency:     @order.amount.currency
  )

  @order.update!(payment: charge.to_json, status: 'paid')
  authorize @order
  redirect_to confirmation_path(@order)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to orders_path
  end

  def confirmation
    @order = Order.find(params[:order_id])
    # user = User.first
    # UserMailer.welcome(user).deliver_now

  end


private

  def set_order
    @order = Order.where(status: 'new').find(params[:order_id])
    #authorize @order
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_after_action :verify_authorized
  skip_before_action :authenticate_user!, only: [:show]

  def show
    @recipe = Recipe.find(params[:recipe_id])
    authorize @recipe
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name

  :user

  end

  def resource

  @resource ||= User.new

  end

  def devise_mapping

  @devise_mapping ||= Devise.mappings[:user]

  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/shared/_basket.html.erb
<div id="site-wrapper">
  <div id="site-menu">
    <div class="basket-content">

      <div class="basket-items" id="basket-items">
        <% if !@order_lines.blank? %>
          <h3 style="margin-bottom: 40px; margin-top: 15px; display: inline-block;">items</h3>
         <span> (<div id="total-id" style="display:inline;"><%=@order_lines.size%></div>&nbsp;items)</span>
          <% @order_lines.each do |item| %>
            <div class="basket-card" id="<%="bask#{item.id.to_s}"%>">
              <div class="basket-card-image" style="background-image: url(<%= item.product.photo %>)">
                <div class="basket-card-producer-avatar" style="background-image: url(<%= item.product.producer.photo %>)">
                </div>
              </div>

                <div class="basket-item-info">
                  <div class="item-info-spacing">
                    <div class="item-name-and-producer">
                      <% product = item.product  %>
                      <% total = product.price*item.quantity%>
                      <% producer = item.product.producer  %>
                      <h3 class="basket-item-producer-info"><%= producer.name %> | <%= producer.city  %></h3>
                      <h3 class="basket-item-name"><%= product.name%></h3>
                      <h3 class="basket-item-producer-info" style="color:#524F4C"><div id="<%="cost#{item.id.to_s}"%>" style="display:inline;"><%=product.price%></div> PER <%= product.unit_type %></h3>
                    </div>


                    <div class="item-price-and-qty">
                      <h3 class="item-qty">QTY:<div id="<%="qty#{item.id.to_s}"%>" style="display:inline"><%= item.quantity %></div></h3>
                      <h3 class="item-price">$<div id="<%="amount#{item.id.to_s}"%>" style="display:inline;"><%=total%></div></h3>

                      <div class="add-controls-basket">
                        <div class="plus-minus-qty" style="background-color:white;">
                          <div>
                            <%= link_to "-", remove_order_lines_path(item.id), method: :get, class: "basket-minus", onclick: "remove_item(#{item.id})", remote: true%>
                          </div>
                        <div>
                           <%= link_to "+", add_order_lines_path(item.id), method: :get, class: "basket-plus", onclick: "add_item(#{item.id})", remote: true%>
                        </div>
                      </div>
                    </div>

                    </div>
                  </div>
                </div>
            </div>
          <% end %>
          <div class="basket-items-spacer"></div>
        <% else %>
          <h3 style="margin-bottom: 40px; margin-top: 15px; display: inline-block;">items</h3>
          <p class="summary-item" style="color: #FFB96E; font-size: 15px; font-weight: 700;">Currently there are no items in your basket</p>
        <% end %>

            <div id="hide-empty" style="display:none">
               <h3 style="margin-bottom: 40px; margin-top: 15px; display: inline-block;">items</h3>
                <p class="summary-item" style="color: #FFB96E; font-size: 12px; font-weight: 700">Currently there are no items in your basket</p>
            </div>
          </div>

      <div class="basket-summary">
        <div class="flex-space-between" id="hide-back">
          <a href="#" class="toggle-nav basket-button"><%= image_tag("Triangle.svg", class: "triangle-icon rotate-triangle-icon") %> GO BACK</a>
          <h3 class="basket-title">BASKET</h3>
        </div>
        <h3 style="margin-bottom: 40px; margin-top: 30px;">summary</h3>
        <div class="flex-space-between summary-div">
          <h3 class="summary-item">Grocery Items</h3>
          <h3 class="summary-item">$<div id="grocery-amount" style="display:inline;"><%=@order.amount%></div></h3>
        </div>
        <div class="flex-space-between summary-div">
          <% delivery_cost = 500  %>
          <h3 class="summary-item">Delivery & Handling</h3>
          <h3 class="summary-item">$5</h3>
        </div>
        <div class="flex-space-between" style="margin-bottom: 40px; margin-top: 50px;">
          <h3 class="basket-button">TOTAL</h3>
          <% @order.amount_cents = @order.amount_cents + delivery_cost %>
          <h3 class="basket-button">AUS $<div id="order_amount" style="display:inline"><%=@order.amount%></div></h3>
        </div>
        <a href="#" class="toggle-checkout basket-button" id="hide-button">CHECKOUT <%= image_tag("Triangle.svg", class: "triangle-icon") %></a>
      </div>

      <div class="checkout checkout-switch" id="checkout">
        <div class="flex-space-between">
          <a href="#" class="toggle-checkout basket-button"><%= image_tag("Triangle.svg", class: "triangle-icon rotate-triangle-icon") %> EDIT BASKET</a>
          <h3 class="basket-title">CHECKOUT</h3>
        </div>
        <div style="display: flex; flex-direction: column; justify-content: space-between; width: 100%; margin-bottom: 40px; margin-top: 15px">
          <div>
            <h3 style="margin-bottom: 20px; width: 100%">delivery details</h3>
          </div>
          <div style="width: 100%; text-align: left; color: #C0C0C0">

            <% contact = current_user.contact %>
            <%= simple_form_for [current_user, @contact], remote: true do |f| %>
            <% if contact.phone.present? && contact.address.present? %>
              <%= f.input :phone, label: false, value:  contact.phone %>
              <%= f.input :address, label: false, value: contact.address , :input_html => { id: "address"} %>
            <% else %>
              <%= f.input :phone, label: false, placeholder: "Phone Number"  %>
              <%= f.input :address, label: false, placeholder: "Delivery Address", :input_html => { id: "address"} %>
              <% end %>
              <div style="display:none;"><%= f.submit "SAVE", class: "confirm_address basket-button"%></div>

            <% end %>
          </div>
        </div>
        <div style="display: flex; flex-direction: column; justify-content: space-between; width: 100%; margin-bottom: 40px; margin-top: 15px">
          <div>
            <h3 style="margin-bottom: 20px; width: 100%">payment</h3>
          </div>

          <script src="https://js.stripe.com/v3/"></script>

          <form action=<%=order_payments_path(@order.id)%> method="post" id="payment-form">

             <input type="hidden" value=<%=current_user.email%>  name= "stripeEmail">

            <div class="form-row">
              <div id="card-element">
                <!-- A Stripe Element will be inserted here. -->
              </div>

              <!-- Used to display Element errors. -->
              <div id="card-errors" role="alert"></div>
            </div>

            <button>Submit Payment</button>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>

<script>

  <% if current_user.contact.nil? || current_user.contact.address.blank? %>
    document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
 <% end %>

  $('#address').blur(function (event) {
    console.log("blurrr");
    document.getElementById("edit_contact_2").submit();
    document.getElementsByClassName("stripe-button-el")[0].style.display = 'inline-block';
  });

</script>


<script>
  // Create a Stripe client.
  var stripe = Stripe("<%= Rails.configuration.stripe[:publishable_key] %>");

  // Create an instance of Elements.
  var elements = stripe.elements({
        font: {
            family:'Montserrat',
            src: "url('https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700')"
        }
    }
  );


  // Custom styling can be passed to options when creating an Element.
  // (Note that this demo uses a wider set of styles than the guide below.)
  var style = {
    base: {
      color: '#524F4C',
      lineHeight: '18px',
      fontSmoothing: 'antialiased',
      fontSize: '14px',
      '::placeholder': {
        color: '#c0c0c0'
      }
    },
    invalid: {
      color: '#FC6565',
      iconColor: '#FC6565'
    }
  };

  // Create an instance of the card Element.
  var card = elements.create('card', {style: style});

  // Add an instance of the card Element into the `card-element` <div>.
  card.mount('#card-element');

  // Handle real-time validation errors from the card Element.
  card.addEventListener('change', function(event) {
    var displayError = document.getElementById('card-errors');
    if (event.error) {
      displayError.textContent = event.error.message;
    } else {
      displayError.textContent = '';
    }
  });

  // Handle form submission.
  var form = document.getElementById('payment-form');
  form.addEventListener('submit', function(event) {
    event.preventDefault();

    stripe.createToken(card).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error.
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the token to your server.
        stripeTokenHandler(result.token);
      }
    });
  });

  function stripeTokenHandler(token) {
    // Insert the token ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeToken');
    hiddenInput.setAttribute('value', token.id);
    form.appendChild(hiddenInput);

    // Submit the form
    form.submit();
  }

















function remove_item(id) {


    var item_quantity = parseInt(document.querySelector(`#qty${id}`).innerHTML);
    var order_amt = parseInt(document.querySelector("#order_amount").innerHTML);
    var item_cost = parseInt(document.querySelector(`#cost${id}`).innerHTML);
    var item_amt = parseInt(document.querySelector(`#amount${id}`).innerHTML);

     if (item_quantity > 1)
     {

    var item_quantity = item_quantity - 1;
    document.querySelector(`#qty${id}`).innerHTML = item_quantity;
    document.querySelector(`#amount${id}`).innerHTML = item_amt - item_cost;
    document.querySelector("#order_amount").innerHTML = order_amt - item_cost;
    document.querySelector("#grocery-amount").innerHTML = order_amt - item_cost;
      }
     else
       {
      document.querySelector(`#bask${id}`).style.display = "none";
      num_item = parseInt(document.querySelector("#total-id").innerHTML);
      order_amt = parseInt(document.querySelector("#order_amount").innerHTML);
      document.querySelector("#order_amount").innerHTML = order_amt - item_cost;
      document.querySelector("#grocery-amount").innerHTML = (order_amt - item_cost)-5;

         if (num_item <= 1)

         {
            document.querySelector(".hide-empty").style.display = "inline";
            document.querySelector(".basket-count-show").innerHTML = `[${num_item}]`;
        }
         else
        {
          document.querySelector(".basket-count-show").innerHTML = `[${num_item}]`;
          document.querySelector("#total-id").innerHTML = num_item - 1;
        }

       }

  }


   function add_item(id) {

    var item_quantity = parseInt(document.querySelector(`#qty${id}`).innerHTML)
    var order_amt = parseInt(document.querySelector("#order_amount").innerHTML);
    var item_cost = parseInt(document.querySelector(`#cost${id}`).innerHTML);
    var item_amt = parseInt(document.querySelector(`#amount${id}`).innerHTML);


    var item_quantity = item_quantity + 1;


    document.querySelector(`#qty${id}`).innerHTML = item_quantity;
    document.querySelector(`#amount${id}`).innerHTML = item_amt + item_cost;

    document.querySelector("#order_amount").innerHTML = order_amt + item_cost;
    document.querySelector("#grocery-amount").innerHTML = (order_amt + item_cost)-5;

  }










</script>

app/views/shared/_category.html.erb
            <%# link_to "Show", product_path(product.id),:style=> 'color:blue'%>

                <% product = @product %>
                <div class="product-card overlay white" style="background:
    linear-gradient(
      rgba(0, 0, 0, 0.45),
      rgba(0, 0, 0, 0)
    ), url(<%=product.photo%>); background-size: cover;">
                  <div class="product-card-content">
                    <h5 class="product-card-title"><div><%= product.producer.name %>'s<br><%= product.name%></div></h5>
                    <p class="product-card-price"> <%=humanized_money_with_symbol(product.price)%></p>
                  </div>
                  <button class="info-button button5" onclick="toggleProduct(<%=product.id.to_s%>)">i</button>
                  <div class="add-controls">
                    <div class="plus-minus-qty">

                      <% if ((!current_user.nil?) && (!current_user.orders.find_by(status: "new").nil?) && (!current_user.orders.find_by(status: "new").order_lines.find_by(product: product.id).nil?)) %>
                        <% orderline = current_user.orders.find_by(status: "new").order_lines.find_by(product: product.id)%>
                        <%= link_to image_tag("minus-icon.svg", size: "16x2"), remove_order_lines_path(orderline.id), method: :get, class: "add_quant"%>
                        <h3 class="qty"><%= orderline.quantity %></h3>
                        <%= link_to image_tag("white-plus-icon.svg", size: "16x16"), add_order_lines_path(orderline.id), method: :get, class: "remove_quant"%>

                      <% else %>
                      <%= link_to "ADD", add_to_basket_path(product.id), class: "add-to-cart-btn"%>
                       <!--  <a href= <%=add_to_basket_path(product.id)%> class="add-to-cart-btn" remote="true">ADD</a> -->
                      <% end %>
                    </div>
                  </div>
                </div>

app/views/shared/_product_page.html.erb
<% if !@product.blank?%>

<% product = @product %>
  <div id="<%= "product#{@product.id.to_s}"%>" class="show-product product-modal" data-spy="scroll" data-target="#myScrollspy" data-offset="20">
    <div class="go-back">
      <a style="display:block" class="toggle-product basket-button" onclick="toggleProduct(<%=product.id.to_s%>)" "><img class="x-icon" src="http://res.cloudinary.com/dat5wdshi/image/upload/v1521729938/plus-icon.svg" alt="Triangle"></a>
    </div>
    <div class="product-page-links" id="myScrollspy">
    </div>
    <div class="product-producer-info-scroll">
      <div class="product-page-section" style="margin-top: 10px;">
        <div style="margin-bottom: 20px; margin-top: 20px">
        <h3 style="display: inline;">our producer </h3><h3 class="basket-button" style="display: inline; color: #FFB96E; margin-bottom: 10px;"><%=@product.producer.name.upcase %></h3>
        <p style="margin-bottom: 5px"><%=@product.producer.description%></p>
      </div>
        <h3 style="display: inline">location</h3>
        <h3 class="basket-button" style="display: inline; color: #FFB96E; margin-bottom: 10px;""><%=@product.producer.city.upcase %></h3>
      </div>
      <div class="card-map" style="background-image: url('https://maps.googleapis.com/maps/api/staticmap?center=<%= @product.producer.latitude %>,<%= @product.producer.longitude %>&markers=color:purple%7C<%= @product.producer.latitude %>,<%= @product.producer.longitude %>&zoom=12&size=2000x1500&key=AIzaSyCKxAu_Y-IhJUSTXAcMghvx_UDSBSGm2l8')";'>
      </div>

      <% unless @product.producer.Farmphotos.empty? %>
      <h3 style="margin-bottom: 7px">photos</h3>
      <div class="producer-gallery">
        <% @product.producer.Farmphotos.each do |photo| %>
        <div class="gallery-photo" style="background-image: url(<%= photo %>)"></div>
          <% end %>
      </div>
      <% end %>


      <div class="product-page-section" id="similar-products">
        <h3>similar products</h3>
        <div class="similar-products">
          <% @three_similar_products = Product.where(category_id: @product.category_id).take(5) %>
          <% @three_similar_products.each do |product| %>
            <div class="product-card overlay white" onclick="toggleProduct(<%=product.id.to_s%>)" style="background:
                linear-gradient(
                  rgba(0, 0, 0, 0.45),
                  rgba(0, 0, 0, 0)
                ), url(<%=product.photo%>); background-size: cover;">
              <div class="product-card-content">
                <h5 class="product-card-title"><%= product.producer.name %>'s<br><%= product.name%></h5>
                <p class="product-card-price"> <%=humanized_money_with_symbol(product.price)%></p>
              </div>
              <div class="add-controls">
                <div class="plus-minus-qty">

                  <% if ((!current_user.nil?) && (!current_user.orders.find_by(status: "new").nil?) && (!current_user.orders.find_by(status: "new").order_lines.find_by(product: product.id).nil?)) %>
                    <% orderline = current_user.orders.find_by(status: "new").order_lines.find_by(product: product.id)%>
                    <%= link_to image_tag("minus-icon.svg", size: "16x2"), remove_order_lines_path(orderline.id), method: :get, class: "add_quant"%>
                    <h3 class="qty"><%= orderline.quantity %></h3>
                    <%= link_to image_tag("white-plus-icon.svg", size: "16x16"), add_order_lines_path(orderline.id), method: :get, class: "remove_quant"%>

                  <% else %>
                    <a href= <%=add_to_basket_path(product.id)%> class="add-to-cart-btn">ADD</a>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <p><%=  %></p>
        </div>
      </div>
      <div class="producer-info-spacer"></div>
    </div>

    <div class="product-info">
      <div class="product-modal-title">
        <h3><%= product.producer.name %>'s<br><%= product.name%></h3>

        <div class="product-page-price">
          <h4 class="product-page-price-label">price</h4>
          <h4 class="product-page-price-number"> <%=humanized_money_with_symbol(product.price)%> per kg</h4>
        </div>
      </div>

      <div class="product-page-add">
        <div class="plus-minus-qty">

          <% if ((!current_user.nil?) && (!current_user.orders.find_by(status: "new").nil?) && (!current_user.orders.find_by(status: "new").order_lines.find_by(product: product.id).nil?)) %>
            <% orderline = current_user.orders.find_by(status: "new").order_lines.find_by(product: product.id)%>
            <%= link_to image_tag("minus-icon.svg", size: "16x2"), remove_order_lines_path(orderline.id), method: :get, class: "add_quant"%>
            <h3 class="qty"><%= orderline.quantity %></h3>
            <%= link_to image_tag("white-plus-icon.svg", size: "16x16"), add_order_lines_path(orderline.id), method: :get, class: "remove_quant"%>

          <% else %>
            <a onclick="location.href='<%=add_to_basket_path(product.id)%>';" class="add-to-cart-btn">ADD</a>
          <% end %>

        </div>


                  <% unless product.nutrient.nil? %>
            <div class "nutrient_table">
              <table style="width:100%">
                <p id="tablehead" style="font-weight: bold">Nutrients per serving:</p>
                <tr>
                  <th></th>
                  <th></th>
                </tr>
                <tr>
                  <td>Fat: </td>
                  <td><%= product.nutrient.fatquant %> / <%= product.nutrient.fatunit %></td>
                </tr>
                <tr>
                  <td>Calories: </td>
                  <td><%= product.nutrient.calquant %> / <%= product.nutrient.calunit %></td>
                </tr>
                <tr>
                  <td>Carbohydrates: </td>
                  <td><%= product.nutrient.carbsquant %> / <%= product.nutrient.carbsunit %></td>
                </tr>
              </table>
            </div>
          <%end %>


            <div class="product-page-section" id="related_recipes">
        <% if @product.recipes.present? %>
        <h3>related recipes</h3>
        <% @product.recipes.each do |recipe| %>

            <a href="<%= recipe_path(recipe.id)%>">
             <div class="gallery-photo" style="background: linear-gradient( rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0)), url(<%=recipe.photo%>); margin: 0px; width: 100%; background-size: cover;">


               <h5 class="farmer-name" style="color:white;padding: 5px;"><%=recipe.title%></h5>

             </div>
             </a>
             <div style="padding-bottom: 5px;"></div>
        <% end %>
        <div>
        </div>
          <% end %>
           </div>

      </div>



    </div>

  </div>
<% end %>

app/views/shared/_recipe_category.html.erb
            <%# link_to "Show", product_path(product.id),:style=> 'color:blue'%>

                <% recipe = @recipe %>
                <div class="recipe-card overlay white" style="background:
    linear-gradient(
      rgba(0, 0, 0, 0.45),
      rgba(0, 0, 0, 0)
    ), url(<%=recipe.photo%>); background-size: cover; background-position: center;">
                  <div class="recipe-card-content">
                    <h5 class="recipe-card-title"><div><%= recipe.producer.name %>'s<br><%= recipe.title%></div></h5>
                  </div>
                  <button class="info-button button5">
                    <%= link_to "i", recipe_path(recipe.id), class: "link-inside-infobtn" %>
                  </button>
                </div>