config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/products/:id/add', to: 'order_lines#add_to_basket', as: 'add_to_basket'
  get '/order_lines/:id/add', to: 'order_lines#add', as: 'add_order_lines'
  get '/order_lines/:id/remove', to: 'order_lines#remove', as: 'remove_order_lines'

  get  "/postcodecheckers", to: "postcodecheckers#check_address"
  get  "/confirmation/:order_id", to: "payments#confirmation", as:"confirmation"
  get  "/about", to: "pages#about", as:"about"
  get  "/recipe/:recipe_id", to: "recipes#show", as:"recipe"
  get "/recipe/:recipe_id/order", to: "order_lines#order_recipe", as: "order_recipe"


  get "/orders/history", to: "orders#history", as: "order_history"
  get "/order_lines/:id/reorder", to: "order_lines#reorder", as: "reorder"

  post   "/subscriptions", to: "pages#create_subscription", as: "subscriptions"


  root to: 'pages#home'
    resources :users, only: [:new, :create, :edit, :update] do
      resources :contacts, only: [:update]
    end
    resources :orders, only: [:index] do
      resources :payments, only: [:new, :create]
    end
    resources :products, only: [:index, :show] do
      resources :order_lines, only: [:create]
    end

    post  "/postcodecheckers", to: "postcodecheckers#check_address"
    get  "/checkout", to: "payments#checkout"

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_lines
  has_many :products, through: :order_lines
  monetize :amount_cents

  validates :status, presence: true, inclusion: ["new","paid"]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end

  def history
    if !current_user.nil?
      @orders = Order.where(user_id: current_user.id)
      authorize @orders
    end
  end
end

app/views/orders/history.html.erb
<div class="history-page">
  <div class="sidenav">
    <a href="<%= products_path  %>" class="basket-button-history"> <%= image_tag("Triangle.svg", class: "triangle-icon rotate-triangle-icon") %> shop</a>
    <!--  <a href="#" class="sidenav-link anchor">cancelled</a> -->
  </div>
  <div class="products-section">
    <h3 class="section-title">my past orders</h3>
    <div class="past-orders-box">
      <% if !@orders.first.payment.nil? %>
        <% @current_user.orders.where(status: "paid").reverse.each_with_index do |order, index| %>
          <% if order.order_lines.count > 0 %>
            <div class="orders-box">
              <div>
                <div>
                <!-- <p style="display: inline-block; margin-top: 30px;">ID <%= index + 1 %></p> -->
                <div class="order-info-box" >
                  <a href="<%= reorder_path(order) %>" class="reorder-btn add-to-cart-btn">
                   repeat order
                 </a>
                      <% product_quantity = 0
                         order.order_lines.each do |line|
                          product_quantity += line.quantity
                         end
                         product_quantity
                       %>
                  <p class="order-date-text">
                    <strong>Ordered on</strong> - <%= order.created_at.day %>/<%= order.created_at.month %>/<%= order.created_at.year %> (<strong><%= product_quantity %> items</strong>)
                  </p>
                <div class="total-cost-text"> <strong>Total:</strong> <%= humanized_money_with_symbol(order.amount)%> </div>
              </div>
              </div>
              <% order.products.each do |product|  %>
              <div class="basket-card history-product-card">
                <div class="basket-card-image" style="background-image: url(<%= product.photo %>)">
                  <div class="basket-card-producer-avatar" style="background-image: url(<%= product.producer.photo %>)">
                  </div>
                </div>
                  <div class="basket-item-info">
                    <div class="item-info-spacing">
                      <div class="item-name-and-producer">
                        <% total = product.price*order.order_lines.find_by(product_id: product.id).quantity%>
                        <h3 class="basket-item-name"><%= product.name%></h3>
                        <h3 class="basket-item-producer-info" style="color:#524F4C">
                          <%= product.price%> PER <%= product.unit_type %>
                        </h3>
                         <% producer = product.producer  %>
                        <h3 class="basket-item-producer-info"><%= producer.name %></h3>
                        <h3 class="basket-item-producer-info"><%= producer.city  %> | 10KM</h3>
                      </div>
                      <div class="item-price-and-qty">
                        <h3 class="item-qty" >QTY: <%= order.order_lines.find_by(product_id: product.id).quantity %></h3>
                        <h3 class="item-price">$<%= total %></h3>
                      </div>
                    </div>
                  </div>
              </div>
            <% end %>
            <% end %>
          <% end %>
        <div class="basket-items-spacer"></div>
      <% else %>
        <p class="summary-item no-items-text">Currently there are no items in your basket</p>
      <% end %>
    </div>
  </div>
  </div>
  </div>
  </div>
  </div>
</div>