config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get '/products/:id/add', to: 'order_lines#add_to_basket', as: 'add_to_basket'
  get '/order_lines/:id/add', to: 'order_lines#add', as: 'add_order_lines'
  get '/order_lines/:id/remove', to: 'order_lines#remove', as: 'remove_order_lines'

  get  "/postcodecheckers", to: "postcodecheckers#check_address"
  get  "/confirmation/:order_id", to: "payments#confirmation", as:"confirmation"
  get  "/about", to: "pages#about", as:"about"
  get  "/recipe/:recipe_id", to: "recipes#show", as:"recipe"
  get "/recipe/:recipe_id/order", to: "order_lines#order_recipe", as: "order_recipe"


  get "/orders/history", to: "orders#history", as: "order_history"
  get "/order_lines/:id/reorder", to: "order_lines#reorder", as: "reorder"

  post   "/subscriptions", to: "pages#create_subscription", as: "subscriptions"


  root to: 'pages#home'
    resources :users, only: [:new, :create, :edit, :update] do
      resources :contacts, only: [:update]
    end
    resources :orders, only: [:index] do
      resources :payments, only: [:new, :create]
    end
    resources :products, only: [:index, :show] do
      resources :order_lines, only: [:create]
    end

    post  "/postcodecheckers", to: "postcodecheckers#check_address"
    get  "/checkout", to: "payments#checkout"

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  skip_after_action :verify_authorized
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!
  before_action :set_order, except: :confirmation

  # def new
  #   @order= Order.find(params[:order_id])
  # end

  def create

    customer = Stripe::Customer.create(
    source: params[:stripeToken],
    email:  params[:stripeEmail]
  )

  charge = Stripe::Charge.create(
    customer:     customer.id,   # You should store this customer id and re-use it.
    amount:       @order.amount_cents,
    description:  "Payment for order #{@order.id}",
    currency:     @order.amount.currency
  )

  @order.update!(payment: charge.to_json, status: 'paid')
  authorize @order
  redirect_to confirmation_path(@order)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to orders_path
  end

  def confirmation
    @order = Order.find(params[:order_id])
    # user = User.first
    # UserMailer.welcome(user).deliver_now

  end


private

  def set_order
    @order = Order.where(status: 'new').find(params[:order_id])
    #authorize @order
  end
end

app/views/payments/confirmation.html.erb
<!-- #empty page
#send email
 -->
<%= image_tag 'kale.png', :class => "kale-confirmation" %>
<%= image_tag 'carrot.png', :class => "carrot-confirmation" %>

<div style="position: fixed; top: 0px; left: 0px; display: flex; width: 100%; height: 100%; justify-content: center; align-items: center">
  <div id="confirmation_card">

    <div id="confirmation_headline">
      <h2>Thanks for shopping.</h2>
    </div>

    <!-- <div id="confirmation-image-center">
      <div id="confirmation-image" style="background-image: url('https://instagram.fmad3-1.fna.fbcdn.net/vp/313e7eb53c0c2aeefdb6226de1bc3cdb/5B37408C/t51.2885-15/e35/26186842_389010881539000_2585585744009494528_n.jpg')";>
      </div>
    </div> -->


    <div class="confirmation_text">
     <% delivery_cost = 500  %>
      <% @order.amount_cents = @order.amount_cents + delivery_cost %>
      <div style="display: flex; flex-direction: row; justify-content: space-between; padding: 10px 10px 0px 10px">
        <h6 style="color: #FFB96E">Order number : 000<%= @order.id %></h6>
        <h6 style="color: #FFB96E">Paid: <%= humanized_money_with_symbol(@order.amount) %></h6>
      </div>
      <p style= "margin-top: 10px; text-align: center;">Your order <strong>will be delivered on <%= @order.updated_at.strftime("%B") %> <%= @order.updated_at.day + 2 %>, <%= @order.updated_at.year %></strong>. Check your email for delivery updates and your purchase receipt.</p>
    </div>

    <div id="confirmation-button">
      <%= link_to "shop more", products_path %>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<!-- app/views/payments/new.html.erb -->
<h1>Purchase of product <%= @order.status %></h1>
<%= form_tag order_payments_path(@order) do %>
  <article>
    <label class="amount">
      <span>Amount: <%= humanized_money_with_symbol(@order.amount) %></span>
    </label>
  </article>


  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="My Order"
    data-email="<%= current_user.email %>"
    data-description="Order <%= @order.order_lines.first.quantity %>"
    data-amount="<%= @order.amount_cents %>"
    data-currency="<%= @order.amount.currency %>"></script>
<% end %>